import Link from "next/link";
import { countActiveOrdersByShop } from "../db/orders";
import { listPublicShops } from "../db/shops";
import { slotState } from "../db/slots";
import { getShopRating } from "../db/reviews";
import AccountChip from "./account-chip";
import { getUser } from "./session";
import { DOSE_DISPLAY_FAMILIES } from "./dose-palette";
import {
  FACTS,
  FAQ,
  HERO,
  NAV,
  NOTICES,
  PALETTE_COPY,
  SHOPS_COPY,
  SITE,
  STEPS,
  WHAT,
} from "./site-content";

export const dynamic = "force-dynamic";

const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;

export default async function Home() {
  const [shops, user] = await Promise.all([
    listPublicShops().catch(() => []),
    getUser().catch(() => null),
  ]);
  const ratings = new Map(await Promise.all(shops.map(async (shop) =>
    [shop.id, await getShopRating(shop.id).catch(() => null)] as const,
  )));
  // One grouped query rather than one per shop.
  const activeOrders = await countActiveOrdersByShop().catch(() => new Map<string, number>());

  return (
    <div className="market-page">
      <header className="market-header">
        <div className="wrap">
          <Link className="brand" href="/">
            <span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>
            <span>{SITE.name}</span>
          </Link>
          <nav className="market-nav" aria-label="주요 메뉴">
            {NAV.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}
          </nav>
          <AccountChip userName={user?.name ?? null} next="/"/>
          <Link className="admin-link" href="/admin">샵 관리자</Link>
        </div>
      </header>

      <main>
        <section className="market-hero" aria-labelledby="hero-title">
          <div className="wrap">
            <div className="market-hero-copy">
              <p className="eyebrow">{HERO.eyebrow}</p>
              <h1 className="display" id="hero-title">
                {HERO.title[0]}<br/>{HERO.title[1]}
              </h1>
              <p className="lede">{HERO.lede}</p>
              <div className="market-hero-actions">
                <a className="btn btn-solid" href="#shops">
                  {HERO.ctaPrimary} <span className="arrow" aria-hidden="true">→</span>
                </a>
                <a className="btn btn-line" href="#how">{HERO.ctaSecondary}</a>
              </div>
            </div>

            <figure className="market-hero-art">
              <div className="hero-canvas">
                {/* Generated by scripts/build-artwork.mjs: drawn, then snapped to Dose.gpl. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src="/art/demo-converted.png" alt={HERO.artAlt} width={160} height={96}/>
              </div>
              <figcaption>
                <span>{HERO.artCaption[0]}</span>
                <span>{HERO.artCaption[1]}</span>
              </figcaption>
            </figure>
          </div>
        </section>

        <section className="market-facts" aria-label="기본 규격">
          <div className="wrap">
            {FACTS.map((fact) => (
              <div key={fact.label}><b>{fact.value}</b><span>{fact.label}</span></div>
            ))}
          </div>
        </section>

        <section className="market-section" id="about">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">{WHAT.eyebrow}</p>
              <h2>{WHAT.title}</h2>
            </div>
            <div className="prose">
              {WHAT.body.map((paragraph) => <p key={paragraph.slice(0, 12)}>{paragraph}</p>)}
            </div>
          </div>
        </section>

        <section className="market-section band" id="how">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">HOW IT WORKS</p>
              <h2>주문까지 네 단계</h2>
            </div>
            <ol className="steps">
              {STEPS.map((step) => (
                <li key={step.no}>
                  <b className="step-no">{step.no}</b>
                  <h3>{step.title}</h3>
                  <p>{step.body}</p>
                </li>
              ))}
            </ol>
          </div>
        </section>

        <section className="market-section" id="shops">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">{SHOPS_COPY.eyebrow}</p>
              <h2>{SHOPS_COPY.title}</h2>
              <p>{SHOPS_COPY.note}</p>
            </div>
            <div className="directory-heading">
              <span>{shops.length}개 운영 중</span>
            </div>
            <div className="shop-grid">
              {shops.map((shop) => (
                <Link className="shop-card" href={`/shop/${shop.slug}/about`} key={shop.id}>
                  <div className="shop-art">
                    {shop.images[0] ? (
                      <>
                        {/* Cover images are uploaded by each shop manager. */}
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={shop.images[0].url} alt={`${shop.name} 작업 예시`}/>
                      </>
                    ) : (
                      <div className="shop-art-empty lattice">
                        <span>{shop.name.slice(0, 2).toUpperCase()}</span>
                        <small>작업 이미지 준비 중</small>
                      </div>
                    )}
                  </div>
                  <div className="shop-card-copy">
                    <div>
                      <small>/{shop.slug}</small>
                      {(() => {
                        const slots = slotState(shop, activeOrders.get(shop.id) ?? 0);
                        if (!shop.webhookConfigured) return <span className="preparing">준비 중</span>;
                        if (slots.full) return <span className="closed">접수 마감</span>;
                        if (slots.enabled) return <span className="ready">슬롯 {slots.used}/{slots.max}</span>;
                        return <span className="ready">주문 가능</span>;
                      })()}
                    </div>
                    <h3>{shop.name}</h3>
                    {(ratings.get(shop.id)?.count ?? 0) > 0 && (
                      <p className="card-rating">
                        <b aria-hidden="true">{"★".repeat(Math.round(ratings.get(shop.id)!.average))}<i>{"★".repeat(5 - Math.round(ratings.get(shop.id)!.average))}</i></b>
                        <strong>{ratings.get(shop.id)!.average.toFixed(1)}</strong>
                        <span>({ratings.get(shop.id)!.count})</span>
                      </p>
                    )}
                    <p>{shop.description || "32×32 캔버스 도안을 만드는 샵입니다."}</p>
                    <b>
                      장당 {won(shop.pricing.tilePrice)}부터
                      <span>자세히 보기 →</span>
                    </b>
                  </div>
                </Link>
              ))}
              {shops.length === 0 && (
                <div className="empty-shops">
                  <b>{SHOPS_COPY.emptyTitle}</b>
                  <span>{SHOPS_COPY.emptyBody}</span>
                </div>
              )}
            </div>
          </div>
        </section>

        <section className="market-section band" id="palette">
          <div className="wrap">
            <div className="palette-layout">
              <div>
                <div className="section-head">
                  <p className="eyebrow">{PALETTE_COPY.eyebrow}</p>
                  <h2>{PALETTE_COPY.title}</h2>
                </div>
                <div className="prose">
                  {PALETTE_COPY.body.map((paragraph) => <p key={paragraph.slice(0, 12)}>{paragraph}</p>)}
                </div>
              </div>
              <div>
                <div className="swatch-wall" role="img" aria-label={`화가 이젤 팔레트 색상표. ${PALETTE_COPY.title}.`}>
                  {DOSE_DISPLAY_FAMILIES.map((family) => (
                    <div className="swatch-ramp" key={family.join()}>
                      {family.map((colour, index) => (
                        <i style={{ background: colour }} key={`${colour}-${index}`}/>
                      ))}
                    </div>
                  ))}
                </div>
                <p className="swatch-note">{PALETTE_COPY.wallNote}</p>
              </div>
            </div>
          </div>
        </section>

        <section className="market-section" id="faq">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">FAQ</p>
              <h2>자주 묻는 질문</h2>
            </div>
            <div className="faq-layout">
              <div className="faq-list">
                {FAQ.map((item) => (
                  <details key={item.q}>
                    <summary>{item.q}</summary>
                    <p>{item.a}</p>
                  </details>
                ))}
              </div>
              <aside className="notice-card">
                <h3>{NOTICES.title}</h3>
                <ul className="notice-list">
                  {NOTICES.items.map((notice) => <li key={notice.slice(0, 12)}>{notice}</li>)}
                </ul>
              </aside>
            </div>
          </div>
        </section>
      </main>

      <footer className="market-footer">
        <div className="wrap">
          <div>
            <Link className="brand" href="/">
              <span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>
              <span>{SITE.name}</span>
            </Link>
            <p>{SITE.footer} · {SITE.domain}</p>
            <p className="site-disclaimer">{SITE.disclaimer}</p>
          </div>
          <nav aria-label="바닥글 메뉴">
            {NAV.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}
            <Link href="/admin">샵 관리자</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
