import Link from "next/link";
import { countActiveOrdersByShop } from "../db/orders";
import { listFeatureRanks, listPublicShops } from "../db/shops";
import { slotState } from "../db/slots";
import { listShopRatings } from "../db/reviews";
import { SHOPS_PER_PAGE, SHOP_SORTS, parsePage, parseSort, sortShops } from "../db/shop-sort";
import AccountChip from "./account-chip";
import ShuffleButton from "./shuffle-button";
import { getUser } from "./session";
import { DOSE_DISPLAY_FAMILIES } from "./dose-palette";
import {
  FACTS,
  FAQ,
  HERO,
  NAV,
  NOTICES,
  PALETTE_COPY,
  SHOPS_COPY,
  SITE,
  STEPS,
  WHAT,
} from "./site-content";

export const dynamic = "force-dynamic";

const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;

const NO_RATING = { average: 0, count: 0, completedOrders: 0 };

export default async function Home({ searchParams }: {
  searchParams: Promise<{ sort?: string; page?: string; seed?: string }>;
}) {
  const params = await searchParams;
  const sort = parseSort(params.sort);

  const [allShops, user, ratings, activeOrders, featureRanks] = await Promise.all([
    listPublicShops().catch(() => []),
    getUser().catch(() => null),
    listShopRatings().catch(() => new Map()),
    countActiveOrdersByShop().catch(() => new Map<string, number>()),
    // Read here and used only for sorting. It is never rendered and never
    // reaches a client component, so nothing on the page reveals it exists.
    listFeatureRanks().catch(() => new Map<string, number>()),
  ]);

  // The shuffle lives in the URL: this page renders more than once per request,
  // so a seed invented here would differ between those renders and the order
  // would not survive hydration. ShuffleButton picks a new one on click.
  const seed = Number.parseInt(params.seed ?? "", 10) || 1;

  const sorted = sortShops(allShops.map((shop) => {
    const slots = slotState(shop, activeOrders.get(shop.id) ?? 0);
    return {
      ...shop,
      slots,
      rating: ratings.get(shop.id) ?? NO_RATING,
      featureRank: featureRanks.get(shop.id) ?? 0,
      orderable: shop.webhookConfigured && !slots.full,
    };
  }), sort, seed);

  const pageCount = Math.max(1, Math.ceil(sorted.length / SHOPS_PER_PAGE));
  const page = Math.min(parsePage(params.page), pageCount);
  const shops = sorted.slice((page - 1) * SHOPS_PER_PAGE, page * SHOPS_PER_PAGE);

  const listHref = (next: { sort?: string; page?: number }) => {
    const query = new URLSearchParams();
    const key = next.sort ?? sort;
    if (key !== "recommended") query.set("sort", key);
    if (next.page && next.page > 1) query.set("page", String(next.page));
    if (key === "random") query.set("seed", String(seed));
    const search = query.toString();
    return `${search ? `/?${search}` : "/"}#shops`;
  };

  return (
    <div className="market-page">
      <header className="market-header">
        <div className="wrap">
          <Link className="brand" href="/">
            <span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>
            <span>{SITE.name}</span>
          </Link>
          <nav className="market-nav" aria-label="주요 메뉴">
            {NAV.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}
          </nav>
          <AccountChip userName={user?.name ?? null} next="/"/>
          <Link className="admin-link" href="/admin">샵 관리자</Link>
        </div>
      </header>

      <main>
        <section className="market-hero" aria-labelledby="hero-title">
          <div className="wrap">
            <div className="market-hero-copy">
              <p className="eyebrow">{HERO.eyebrow}</p>
              <h1 className="display" id="hero-title">
                {HERO.title[0]}<br/>{HERO.title[1]}
              </h1>
              <p className="lede">{HERO.lede}</p>
              <div className="market-hero-actions">
                <a className="btn btn-solid" href="#shops">
                  {HERO.ctaPrimary} <span className="arrow" aria-hidden="true">→</span>
                </a>
                <a className="btn btn-line" href="#how">{HERO.ctaSecondary}</a>
              </div>
            </div>

            <figure className="market-hero-art">
              <div className="hero-canvas">
                {/* Generated by scripts/build-artwork.mjs: drawn, then snapped to Dose.gpl. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src="/art/demo-converted.png" alt={HERO.artAlt} width={160} height={96}/>
              </div>
              <figcaption>
                <span>{HERO.artCaption[0]}</span>
                <span>{HERO.artCaption[1]}</span>
              </figcaption>
            </figure>
          </div>
        </section>

        <section className="market-facts" aria-label="기본 규격">
          <div className="wrap">
            {FACTS.map((fact) => (
              <div key={fact.label}><b>{fact.value}</b><span>{fact.label}</span></div>
            ))}
          </div>
        </section>

        <section className="market-section" id="about">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">{WHAT.eyebrow}</p>
              <h2>{WHAT.title}</h2>
            </div>
            <div className="prose">
              {WHAT.body.map((paragraph) => <p key={paragraph.slice(0, 12)}>{paragraph}</p>)}
            </div>
          </div>
        </section>

        <section className="market-section band" id="how">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">HOW IT WORKS</p>
              <h2>주문까지 네 단계</h2>
            </div>
            <ol className="steps">
              {STEPS.map((step) => (
                <li key={step.no}>
                  <b className="step-no">{step.no}</b>
                  <h3>{step.title}</h3>
                  <p>{step.body}</p>
                </li>
              ))}
            </ol>
          </div>
        </section>

        <section className="market-section" id="shops">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">{SHOPS_COPY.eyebrow}</p>
              <h2>{SHOPS_COPY.title}</h2>
              <p>{SHOPS_COPY.note}</p>
            </div>
            <div className="directory-heading">
              <span>{sorted.length}개 운영 중{pageCount > 1 && ` · ${page}/${pageCount} 쪽`}</span>
              {sorted.length > 1 && (
                <nav className="shop-sort" aria-label="샵 정렬">
                  {SHOP_SORTS.map((option) => option.key === "random" ? (
                    <ShuffleButton
                      key={option.key}
                      active={sort === "random"}
                      label={option.label}
                      hint={option.hint}
                    />
                  ) : (
                    <Link
                      key={option.key}
                      href={listHref({ sort: option.key, page: 1 })}
                      className={option.key === sort ? "active" : ""}
                      aria-current={option.key === sort ? "true" : undefined}
                      title={option.hint}
                      scroll={false}
                    >
                      {option.label}
                    </Link>
                  ))}
                </nav>
              )}
            </div>
            <div className={`shop-grid${shops.length === 1 ? " solo" : ""}`}>
              {shops.map((shop) => (
                // An article, not a Link: the rating below is its own link to
                // the reviews, and an anchor inside an anchor is invalid HTML.
                // The title link is stretched over the card instead, so the
                // whole tile still opens the shop.
                <article className="shop-card" key={shop.id}>
                  <div className="shop-art">
                    {shop.images[0] ? (
                      <>
                        {/* Cover images are uploaded by each shop manager. */}
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={shop.images[0].url} alt={`${shop.name} 작업 예시`}/>
                      </>
                    ) : (
                      <div className="shop-art-empty lattice">
                        <span>{shop.name.slice(0, 2).toUpperCase()}</span>
                        <small>작업 이미지 준비 중</small>
                      </div>
                    )}
                  </div>
                  <div className="shop-card-copy">
                    <div>
                      {shop.premium
                        ? <small className="shop-premium">PREMIUM</small>
                        : <small>/{shop.slug}</small>}
                      {!shop.webhookConfigured ? <span className="preparing">준비 중</span>
                        : shop.slots.full ? <span className="closed">접수 마감</span>
                        : shop.slots.enabled ? <span className="ready">슬롯 {shop.slots.used}/{shop.slots.max}</span>
                        : <span className="ready">주문 가능</span>}
                    </div>
                    <h3><Link className="shop-card-open" href={`/shop/${shop.slug}/about`}>{shop.name}</Link></h3>
                    {shop.rating.count > 0 && (
                      <Link className="card-rating" href={`/shop/${shop.slug}/about#reviews`}>
                        <b aria-hidden="true">{"★".repeat(Math.round(shop.rating.average))}<i>{"★".repeat(5 - Math.round(shop.rating.average))}</i></b>
                        <strong>{shop.rating.average.toFixed(1)}</strong>
                        <span>({shop.rating.count})</span>
                        <em>후기 보기</em>
                      </Link>
                    )}
                    {/* One element, not a paragraph per line: each would become
                        its own grid item and space itself out by the grid gap. */}
                    <p className="shop-card-desc">{shop.description || "32×32 캔버스 도안을 만드는 샵입니다."}</p>
                    <b>
                      장당 {won(shop.pricing.tilePrice)}부터
                      <span>자세히 보기 →</span>
                    </b>
                  </div>
                </article>
              ))}
              {shops.length === 0 && (
                <div className="empty-shops">
                  <b>{SHOPS_COPY.emptyTitle}</b>
                  <span>{SHOPS_COPY.emptyBody}</span>
                </div>
              )}
              {/* An empty slot at the end of the list, on the last page only, so
                  the grid reads as "these shops, and room for yours". */}
              {page === pageCount && (
                <Link className="shop-cta" href="/apply">
                  <span className="shop-cta-plus" aria-hidden="true">+</span>
                  <b>{SHOPS_COPY.joinTitle}</b>
                  <span className="shop-cta-hint">{SHOPS_COPY.joinHint}</span>
                </Link>
              )}
            </div>
            {pageCount > 1 && (
              <nav className="shop-paging" aria-label="샵 목록 페이지">
                <Link
                  href={listHref({ page: page - 1 })}
                  className={page === 1 ? "disabled" : ""}
                  aria-disabled={page === 1 ? "true" : undefined}
                  scroll={false}
                >← 이전</Link>
                <span>{page} / {pageCount}</span>
                <Link
                  href={listHref({ page: page + 1 })}
                  className={page === pageCount ? "disabled" : ""}
                  aria-disabled={page === pageCount ? "true" : undefined}
                  scroll={false}
                >다음 →</Link>
              </nav>
            )}
          </div>
        </section>

        <section className="market-section band" id="palette">
          <div className="wrap">
            <div className="palette-layout">
              <div>
                <div className="section-head">
                  <p className="eyebrow">{PALETTE_COPY.eyebrow}</p>
                  <h2>{PALETTE_COPY.title}</h2>
                </div>
                <div className="prose">
                  {PALETTE_COPY.body.map((paragraph) => <p key={paragraph.slice(0, 12)}>{paragraph}</p>)}
                </div>
              </div>
              <div>
                <div className="swatch-wall" role="img" aria-label={`화가 이젤 팔레트 색상표. ${PALETTE_COPY.title}.`}>
                  {DOSE_DISPLAY_FAMILIES.map((family) => (
                    <div className="swatch-ramp" key={family.join()}>
                      {family.map((colour, index) => (
                        <i style={{ background: colour }} key={`${colour}-${index}`}/>
                      ))}
                    </div>
                  ))}
                </div>
                <p className="swatch-note">{PALETTE_COPY.wallNote}</p>
              </div>
            </div>
          </div>
        </section>

        <section className="market-section" id="faq">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">FAQ</p>
              <h2>자주 묻는 질문</h2>
            </div>
            <div className="faq-layout">
              <div className="faq-list">
                {FAQ.map((item) => (
                  <details key={item.q}>
                    <summary>{item.q}</summary>
                    <p>{item.a}</p>
                  </details>
                ))}
              </div>
              <aside className="notice-card">
                <h3>{NOTICES.title}</h3>
                <ul className="notice-list">
                  {NOTICES.items.map((notice) => <li key={notice.slice(0, 12)}>{notice}</li>)}
                </ul>
              </aside>
            </div>
          </div>
        </section>
      </main>

      <footer className="market-footer">
        <div className="wrap">
          <div>
            <Link className="brand" href="/">
              <span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>
              <span>{SITE.name}</span>
            </Link>
            <p>{SITE.footer} · {SITE.domain}</p>
            <p className="site-disclaimer">{SITE.disclaimer}</p>
          </div>
          <nav aria-label="바닥글 메뉴">
            {NAV.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}
            <Link href="/admin">샵 관리자</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
