import Link from "next/link";
import { listPublicShops } from "../db/shops";
import { DEFAULT_PRICING } from "../db/pricing";
import { DOSE_DISPLAY_FAMILIES } from "./dose-palette";
import {
  FACTS,
  FAQ,
  HERO,
  NAV,
  NOTICES,
  PALETTE_COPY,
  PRICING_COPY,
  SHOPS_COPY,
  SITE,
  STEPS,
  WHAT,
} from "./site-content";

export const dynamic = "force-dynamic";

const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;

// Mirrors the studio's rounding so the worked example here and the number in the
// order summary can never drift apart.
const quote = (tiles: number, tilePrice: number, multiplier: number) =>
  Math.round((tiles * tilePrice * multiplier) / 100) * 100;

const DEADLINES = [7, 6, 5, 4, 3, 2, 1];
const EXAMPLE_TILES = 35;

export default async function Home() {
  const shops = await listPublicShops().catch(() => []);
  const { tilePrice, deadlineMultipliers } = DEFAULT_PRICING;
  const exampleTotal = quote(EXAMPLE_TILES, tilePrice, deadlineMultipliers["7"]);

  return (
    <div className="market-page">
      <header className="market-header">
        <div className="wrap">
          <Link className="brand" href="/">
            <span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>
            <span>{SITE.name}</span>
          </Link>
          <nav className="market-nav" aria-label="주요 메뉴">
            {NAV.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}
          </nav>
          <Link className="admin-link" href="/admin">샵 관리자</Link>
        </div>
      </header>

      <main>
        <section className="market-hero" aria-labelledby="hero-title">
          <div className="wrap">
            <div className="market-hero-copy">
              <p className="eyebrow">{HERO.eyebrow}</p>
              <h1 className="display" id="hero-title">
                {HERO.title[0]}<br/>{HERO.title[1]}
              </h1>
              <p className="lede">{HERO.lede}</p>
              <div className="market-hero-actions">
                {shops[0] ? (
                  <Link className="btn btn-solid" href={`/shop/${shops[0].slug}`}>
                    {HERO.ctaPrimary} <span className="arrow" aria-hidden="true">→</span>
                  </Link>
                ) : (
                  <a className="btn btn-solid" href="#shops">
                    {HERO.ctaPrimary} <span className="arrow" aria-hidden="true">→</span>
                  </a>
                )}
                <a className="btn btn-line" href="#price">{HERO.ctaSecondary}</a>
              </div>
            </div>

            <figure className="market-hero-art">
              <div className="hero-canvas">
                {/* Generated by scripts/build-artwork.mjs: drawn, then snapped to Dose.gpl. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src="/art/demo-converted.png" alt={HERO.artAlt} width={160} height={96}/>
              </div>
              <figcaption>
                <span>{HERO.artCaption[0]}</span>
                <span>{HERO.artCaption[1]}</span>
              </figcaption>
            </figure>
          </div>
        </section>

        <section className="market-facts" aria-label="기본 규격">
          <div className="wrap">
            {FACTS.map((fact) => (
              <div key={fact.label}><b>{fact.value}</b><span>{fact.label}</span></div>
            ))}
          </div>
        </section>

        <section className="market-section" id="about">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">{WHAT.eyebrow}</p>
              <h2>{WHAT.title}</h2>
            </div>
            <div className="prose">
              {WHAT.body.map((paragraph) => <p key={paragraph.slice(0, 12)}>{paragraph}</p>)}
            </div>
          </div>
        </section>

        <section className="market-section band" id="how">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">HOW IT WORKS</p>
              <h2>주문까지 네 단계</h2>
            </div>
            <ol className="steps">
              {STEPS.map((step) => (
                <li key={step.no}>
                  <b className="step-no">{step.no}</b>
                  <h3>{step.title}</h3>
                  <p>{step.body}</p>
                </li>
              ))}
            </ol>
          </div>
        </section>

        <section className="market-section" id="price">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">{PRICING_COPY.eyebrow}</p>
              <h2>{PRICING_COPY.title}</h2>
              <p>{PRICING_COPY.body}</p>
            </div>

            <div className="price-layout">
              <table className="price-table">
                <caption>{PRICING_COPY.tableCaption}</caption>
                <thead>
                  <tr>
                    <th scope="col">마감</th>
                    <th scope="col">배수</th>
                    <th scope="col">캔버스 {EXAMPLE_TILES}장 기준</th>
                  </tr>
                </thead>
                <tbody>
                  {DEADLINES.map((day) => {
                    const multiplier = deadlineMultipliers[String(day)];
                    return (
                      <tr className={day === 7 ? "base" : undefined} key={day}>
                        <th scope="row">{day}일</th>
                        <td className={multiplier > 1 ? "rush" : undefined}>×{multiplier.toFixed(2)}</td>
                        <td>{won(quote(EXAMPLE_TILES, tilePrice, multiplier))}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>

              <div className="price-example">
                <h3>{PRICING_COPY.exampleTitle}</h3>
                <dl>
                  <div><dt>가로 칸 수</dt><dd>5칸 · 160px</dd></div>
                  <div><dt>세로 칸 수</dt><dd>7칸 · 224px</dd></div>
                  <div><dt>캔버스</dt><dd>5 × 7 = {EXAMPLE_TILES}장</dd></div>
                  <div><dt>장당</dt><dd>{won(tilePrice)}</dd></div>
                  <div><dt>마감 7일</dt><dd>×{deadlineMultipliers["7"].toFixed(2)}</dd></div>
                  <div className="sum"><dt>합계</dt><dd>{won(exampleTotal)}</dd></div>
                </dl>
                <p>{PRICING_COPY.exampleNote}</p>
                <p>{PRICING_COPY.rounding}</p>
              </div>
            </div>
          </div>
        </section>

        <section className="market-section band" id="shops">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">{SHOPS_COPY.eyebrow}</p>
              <h2>{SHOPS_COPY.title}</h2>
              <p>{SHOPS_COPY.note}</p>
            </div>
            <div className="directory-heading">
              <span>{shops.length}개 운영 중</span>
            </div>
            <div className="shop-grid">
              {shops.map((shop) => (
                <Link className="shop-card" href={`/shop/${shop.slug}/about`} key={shop.id}>
                  <div className="shop-art">
                    {shop.images[0] ? (
                      <>
                        {/* Cover images are uploaded by each shop manager. */}
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img src={shop.images[0].url} alt={`${shop.name} 작업 예시`}/>
                      </>
                    ) : (
                      <div className="shop-art-empty lattice">
                        <span>{shop.name.slice(0, 2).toUpperCase()}</span>
                        <small>작업 이미지 준비 중</small>
                      </div>
                    )}
                  </div>
                  <div className="shop-card-copy">
                    <div>
                      <small>/{shop.slug}</small>
                      <span className={shop.webhookConfigured ? "ready" : "preparing"}>
                        {shop.webhookConfigured ? "주문 가능" : "준비 중"}
                      </span>
                    </div>
                    <h3>{shop.name}</h3>
                    <p>{shop.description || "32×32 캔버스 도안을 만드는 샵입니다."}</p>
                    <b>
                      장당 {won(shop.pricing.tilePrice)}부터
                      <span>자세히 보기 →</span>
                    </b>
                  </div>
                </Link>
              ))}
              {shops.length === 0 && (
                <div className="empty-shops">
                  <b>{SHOPS_COPY.emptyTitle}</b>
                  <span>{SHOPS_COPY.emptyBody}</span>
                </div>
              )}
            </div>
          </div>
        </section>

        <section className="market-section" id="palette">
          <div className="wrap">
            <div className="palette-layout">
              <div>
                <div className="section-head">
                  <p className="eyebrow">{PALETTE_COPY.eyebrow}</p>
                  <h2>{PALETTE_COPY.title}</h2>
                </div>
                <div className="prose">
                  {PALETTE_COPY.body.map((paragraph) => <p key={paragraph.slice(0, 12)}>{paragraph}</p>)}
                </div>
              </div>
              <div>
                <div className="swatch-wall" role="img" aria-label={`화가 이젤 팔레트 색상표. ${PALETTE_COPY.title}.`}>
                  {DOSE_DISPLAY_FAMILIES.map((family) => (
                    <div className="swatch-ramp" key={family.join()}>
                      {family.map((colour, index) => (
                        <i style={{ background: colour }} key={`${colour}-${index}`}/>
                      ))}
                    </div>
                  ))}
                </div>
                <p className="swatch-note">{PALETTE_COPY.wallNote}</p>
              </div>
            </div>
          </div>
        </section>

        <section className="market-section band" id="faq">
          <div className="wrap">
            <div className="section-head">
              <p className="eyebrow">FAQ</p>
              <h2>자주 묻는 질문</h2>
            </div>
            <div className="faq-layout">
              <div className="faq-list">
                {FAQ.map((item) => (
                  <details key={item.q}>
                    <summary>{item.q}</summary>
                    <p>{item.a}</p>
                  </details>
                ))}
              </div>
              <aside className="notice-card">
                <h3>{NOTICES.title}</h3>
                <ul className="notice-list">
                  {NOTICES.items.map((notice) => <li key={notice.slice(0, 12)}>{notice}</li>)}
                </ul>
              </aside>
            </div>
          </div>
        </section>
      </main>

      <footer className="market-footer">
        <div className="wrap">
          <div>
            <Link className="brand" href="/">
              <span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>
              <span>{SITE.name}</span>
            </Link>
            <p>{SITE.footer} · {SITE.domain}</p>
          </div>
          <nav aria-label="바닥글 메뉴">
            {NAV.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}
            <Link href="/admin">샵 관리자</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
